import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { fetchItems } from "../api";
import Navbar from "../components/Navbar";
import type { Item, MovieEntry } from "../types";

const posterBase = "https://image.tmdb.org/t/p/w342";
const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
type Count = { label: string; count: number };

function counts(values: (string | undefined)[]) { const valuesByLabel = new Map<string, number>(); values.filter((value): value is string => Boolean(value?.trim())).forEach((value) => { const label = value.trim(); valuesByLabel.set(label, (valuesByLabel.get(label) ?? 0) + 1); }); return [...valuesByLabel].map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count || a.label.localeCompare(b.label)); }
function rating(items: MovieEntry[]) { const rated = items.filter((item) => item.rating !== null); return rated.length ? (rated.reduce((sum, item) => sum + (item.rating ?? 0), 0) / rated.length).toFixed(1) : "—"; }

function YearbookPage() {
  const navigate = useNavigate(); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const currentYear = new Date().getFullYear(); const [year, setYear] = useState(currentYear);
  useEffect(() => { fetchItems().then(setItems).catch(() => setError("Couldn't load your Yearbook.")).finally(() => setLoading(false)); }, []);
  const years = useMemo(() => [...new Set([currentYear, ...items.map((item) => item.completedYear).filter((value): value is number => Boolean(value))])].sort((a, b) => b - a), [currentYear, items]);
  const films = useMemo(() => items.filter((item): item is MovieEntry => item.type === "movie" && item.status === "done" && item.completedYear === year), [items, year]);
  const previous = useMemo(() => items.filter((item): item is MovieEntry => item.type === "movie" && item.status === "done" && item.completedYear === year - 1), [items, year]);
  const byMonth = months.map((label, index) => ({ label, films: films.filter((film) => film.completedMonth === index + 1) }));
  const exact = films.filter((film) => film.completedDatePrecision === "exact" && film.completedMonth && film.completedDay);
  const byDay = days.map((label, index) => ({ label, count: exact.filter((film) => new Date(year, (film.completedMonth ?? 1) - 1, film.completedDay).getDay() === (index + 1) % 7).length }));
  const genres = counts(films.flatMap((film) => film.genre?.split(",") ?? [])); const platforms = counts(films.map((film) => film.whereWatched)); const tags = counts(films.map((film) => film.sumUpInOneWord));
  const eras = counts(films.map((film) => film.releaseYear ? `${Math.floor(film.releaseYear / 10) * 10}s` : undefined)); const ratings = [5, 4, 3, 2, 1].map((value) => ({ label: "★".repeat(value), count: films.filter((film) => film.rating === value).length }));
  const maxMonth = Math.max(1, ...byMonth.map((entry) => entry.films.length)); const maxDay = Math.max(1, ...byDay.map((entry) => entry.count)); const maxList = Math.max(1, ...genres.map((entry) => entry.count), ...eras.map((entry) => entry.count), ...ratings.map((entry) => entry.count));
  const busiest = byMonth.reduce((top, entry) => entry.films.length > top.films.length ? entry : top, byMonth[0]); const commonRating = ratings.find((entry) => entry.count > 0); const topGenre = genres[0];
  const standouts = [...films].filter((film) => film.rating !== null).sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0) || a.title.localeCompare(b.title)).slice(0, 3);
  const averageChange = Number(rating(films)) - Number(rating(previous));

  return <main className="min-h-screen bg-[#fbf2e5] text-[#352218]"><Navbar onAdd={() => navigate("/shelf", { state: { openAddForm: true } })} showForm={false} /><div className="mx-auto max-w-7xl px-6 pb-20 lg:px-10">
    <section className="flex flex-col gap-7 pt-12 sm:pt-16 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-hand text-xl text-[#b4442a]">年 · what my year of watching says about me</p><h1 className="mt-2 font-serif text-5xl leading-none sm:text-6xl lg:text-7xl">The {year} Yearbook</h1></div><div className="flex flex-wrap gap-2 text-sm text-[#715d4e]">{years.map((value) => <button key={value} type="button" onClick={() => setYear(value)} className={`rounded-full px-4 py-2.5 ${year === value ? "bg-[#4a2c1c] text-[#fff8ef]" : "hover:bg-[#f0e3d0]"}`}>{value}</button>)}</div></section>
    {error && <p className="mt-8 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{loading ? <p className="py-28 text-center text-sm text-[#806858]">Gathering your year…</p> : !films.length ? <EmptyYear year={year} /> : <>
      <section className="mt-12 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Watched" value={String(films.length)} note={previous.length ? `${films.length - previous.length >= 0 ? "+" : ""}${films.length - previous.length} vs ${year - 1}` : "films completed"} /><Stat label="Average rating" value={rating(films) === "—" ? "—" : `${rating(films)}★`} note={previous.length && rating(films) !== "—" && rating(previous) !== "—" ? `${averageChange >= 0 ? "+" : ""}${averageChange.toFixed(1)} vs ${year - 1}` : "rated films only"} /><Stat label="Exact dates saved" value={String(exact.length)} note={exact.length ? "used in the weekday chart" : "add dates to reveal patterns"} /><Stat label="Genres explored" value={String(genres.length)} note={topGenre ? `${topGenre.label} appeared most` : "metadata fills this in"} /></section>
      <section className="mt-20"><SectionTitle title="Things I noticed" note="little patterns in my watching" /><div className="mt-10 grid gap-6 lg:grid-cols-3"><Insight title={busiest.films.length ? busiest.label : "Dates missing"} copy={busiest.films.length ? `${busiest.films.length} ${busiest.films.length === 1 ? "film was" : "films were"} finished in ${busiest.label}.` : "Add a completion month to reveal your busiest time."} /><Insight title={topGenre?.label ?? "Genres to come"} copy={topGenre ? `${topGenre.count} ${topGenre.count === 1 ? "film" : "films"} carried this genre.` : "Genre insights appear when titles have metadata."} /><Insight title={commonRating ? `${commonRating.label} rating` : "Ratings to come"} copy={commonRating ? `${commonRating.count} ${commonRating.count === 1 ? "film earned" : "films earned"} your most common rating.` : "Rate completed films to see your pattern."} /></div></section>
      <section className="mt-20"><SectionTitle title="Month by month" note={`${films.length} watched · average rating above each month`} /><div className="mt-7 grid grid-cols-6 gap-x-2 gap-y-8 sm:grid-cols-12 sm:gap-x-4">{byMonth.map((entry) => <div key={entry.label} className="flex min-w-0 flex-col items-center justify-end"><span className="mb-1 text-xs text-[#b4442a]">{entry.films.length ? rating(entry.films) : ""}</span><span className="mb-2 text-sm font-semibold">{entry.films.length || ""}</span><div className="flex h-36 w-full items-end border-b-4 border-[#4a2c1c]"><div className="w-full rounded-t-sm bg-[#593522] shadow-[inset_0_-18px_0_rgba(140,98,64,.36)]" style={{ height: `${Math.max(entry.films.length ? 12 : 0, (entry.films.length / maxMonth) * 100)}%` }} /></div><span className="mt-3 text-sm text-[#806858]">{entry.label}</span></div>)}</div></section>
      <section className="mt-20 grid gap-x-18 gap-y-16 lg:grid-cols-2"><MetricList title="Genres" note="how often I watched each" entries={genres} max={maxList} /><MetricList title="How I rate" note="what my stars look like" entries={ratings} max={maxList} /><section><SectionTitle title="When I watch" note="exact completion dates only" /><div className="mt-8 flex h-48 items-end gap-4 border-b-4 border-[#4a2c1c] px-5">{byDay.map((entry) => <div key={entry.label} className="flex h-full flex-1 flex-col items-center justify-end"><span className="mb-2 text-sm font-semibold">{entry.count || ""}</span><div className="w-full max-w-10 rounded-t-sm bg-[#593522]" style={{ height: `${Math.max(entry.count ? 10 : 0, (entry.count / maxDay) * 100)}%` }} /><span className="mt-4 text-sm text-[#806858]">{entry.label}</span></div>)}</div></section><MetricList title="Which era" note="release decade of what I watched" entries={eras} max={maxList} /></section>
      <section className="mt-20"><SectionTitle title="Where I watched" note="saved with each film" />{platforms.length ? <><div className="mt-6 flex h-8 overflow-hidden rounded-sm border border-[#e1cfb7]">{platforms.map((entry, index) => <div key={entry.label} className="border-r border-[#fbf2e5] last:border-0" style={{ width: `${(entry.count / films.length) * 100}%`, backgroundColor: ["#4a2c1c", "#765034", "#a87748", "#c8a16e", "#dfc99a"][index % 5] }} title={`${entry.label}: ${entry.count}`} />)}</div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm">{platforms.map((entry) => <span key={entry.label}>{entry.label} <strong>{entry.count}</strong></span>)}</div></> : <p className="mt-6 text-sm text-[#806858]">No viewing locations saved yet.</p>}</section>
      <section className="mt-20 grid gap-16 lg:grid-cols-[.85fr_1.15fr]"><div><SectionTitle title="Tags I hung most" note="one-word takeaways" /><div className="mt-7 flex flex-wrap gap-4">{tags.length ? tags.slice(0, 8).map((entry) => <span key={entry.label} className="rounded-sm bg-[#fffaf2] px-4 py-2 font-hand text-xl text-[#5b3a25] shadow-md">{entry.label} <small className="font-sans text-xs text-[#806858]">×{entry.count}</small></span>) : <p className="text-sm text-[#806858]">Add a one-word takeaway to your entries to collect them here.</p>}</div></div><div><SectionTitle title="Standouts" note="your highest-rated films" /><div className="mt-7 grid gap-5 sm:grid-cols-3">{standouts.map((film, index) => <button key={film.id} type="button" onClick={() => navigate(`/item/${film.id}`)} className="text-left"><div className="aspect-[.72] overflow-hidden rounded-sm border border-[#dfcfba] bg-[#e8dac4]">{film.posterPath ? <img src={posterBase + film.posterPath} alt={`${film.title} poster`} className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center p-4 text-center font-serif text-sm text-[#806858]">{film.title}</div>}</div><p className="mt-3 text-[10px] font-bold uppercase tracking-[.16em] text-[#b4442a]">{["Favorite of the year", "Highly rated", "Worth remembering"][index]}</p><h3 className="mt-1 font-serif text-xl leading-tight">{film.title}</h3><p className="text-sm text-[#806858]">{"★".repeat(film.rating ?? 0)} {film.sumUpInOneWord ? `· “${film.sumUpInOneWord}”` : ""}</p></button>)}</div></div></section>
    </>}</div></main>;
}
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <article className="rounded-xl bg-[#4a2c1c] px-6 py-5 text-[#fff2da]"><p className="text-sm tracking-wide text-[#dfbf92]">{label}</p><p className="mt-2 font-serif text-5xl leading-none">{value}</p><p className="mt-2 text-sm text-[#e5c07d]">{note}</p></article>; }
function SectionTitle({ title, note }: { title: string; note: string }) { return <div className="flex flex-wrap items-end justify-between gap-3 border-b border-[#806858] pb-3"><h2 className="font-serif text-3xl sm:text-4xl">{title}</h2><p className="text-sm text-[#806858]">{note}</p></div>; }
function Insight({ title, copy }: { title: string; copy: string }) { return <article className="rounded-xl border border-[#e5d5c1] bg-[#fffaf2] p-6 shadow-[0_8px_12px_-10px_rgba(58,34,20,.45)]"><p className="font-serif text-3xl text-[#b4442a]">{title}</p><p className="mt-3 text-lg leading-7">{copy}</p></article>; }
function MetricList({ title, note, entries, max }: { title: string; note: string; entries: Count[]; max: number }) { return <section><SectionTitle title={title} note={note} /><div className="mt-6 space-y-4">{entries.length ? entries.slice(0, 6).map((entry) => <div key={entry.label} className="grid grid-cols-[7rem_1fr_1.5rem] items-center gap-3 text-sm"><span className="truncate">{entry.label}</span><div className="h-4 overflow-hidden rounded-sm bg-[#eadfce]"><div className="h-full bg-[#593522] shadow-[inset_0_-6px_rgba(140,98,64,.45)]" style={{ width: `${(entry.count / max) * 100}%` }} /></div><strong>{entry.count}</strong></div>) : <p className="text-sm text-[#806858]">Not enough saved details yet.</p>}</div></section>; }
function EmptyYear({ year }: { year: number }) { return <section className="mt-12 rounded-xl border border-dashed border-[#cbb8a1] bg-[#fffaf2] px-6 py-16 text-center"><h2 className="font-serif text-3xl">No completed films for {year} yet</h2><p className="mx-auto mt-3 max-w-md text-[#806858]">Finish an item and save its completion year to begin filling this Yearbook.</p></section>; }
export default YearbookPage;
